Repository MLH-Fellowship/SocioMark, pull requests merged in 2021-04, with the labels that each got.

#33 Add React Frontend
  frontend/.gitignore
  frontend/README.md
  frontend/craco.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.js
  frontend/src/Components/Account/Login.js
  frontend/src/Components/Account/Register.js
  frontend/src/Components/Common/Home.js
  frontend/src/Components/Common/Navbar.js
  frontend/src/Router/PublicRouter.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/reportWebVitals.js
  frontend/tailwind.config.js
Labels: client, enhancement

#34 Enable CORS
  backend/app/server/app.py
Labels: client, enhancement, server

#35 UI and API integeration for login and register pages
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Account/Login.js
  frontend/src/Components/Account/Register.js
Labels: client, enhancement

#37 Deduplication of data, Implement getting Likes (for Posts) and Posts (for Users)
  backend/app/server/controllers/like.py
  backend/app/server/controllers/post.py
  backend/app/server/controllers/user.py
  backend/app/server/models/post.py
  backend/app/server/models/user.py
Labels: bug, enhancement, maintenance, server

#38 Implement Comments API for posts
  backend/app/server/app.py
  backend/app/server/controllers/comment.py
  backend/app/server/controllers/post.py
  backend/app/server/database.py
  backend/app/server/models/comment.py
  backend/app/server/routes/comment.py
Labels: enhancement, server

#44 Integrate Image Upload for Registering API
  backend/app/server/controllers/upload.py
  backend/app/server/routes/user.py
  backend/requirements.txt
  frontend/src/Components/Account/Register.js
Labels: bug, client, enhancement, server

#49 Update `/post/create` with image upload
  backend/app/server/routes/post.py
Labels: enhancement, server

#54 Server Cleanup, simple UI for backend
  backend/app/server/app.py
  backend/app/server/controllers/like.py
  backend/app/server/controllers/user.py
  backend/app/server/routes/comment.py
  backend/app/server/routes/like.py
  backend/app/server/routes/posts.py
  backend/app/server/routes/suggestions.py
  backend/app/server/routes/user.py
  backend/app/server/routes/users.py
Labels: enhancement, server

#55 Deployed Backend on Heroku
  backend/Procfile
  backend/app/server/controllers/upload.py
  backend/app/server/database.py
Labels: server

#56 Bugfix: lightweight without like_id
  backend/app/server/controllers/like.py
  backend/app/server/controllers/upload.py
  backend/app/server/database.py
Labels: bug, server

#58 Add Loader Component
  frontend/src/Components/Account/Login.js
  frontend/src/Components/Account/Register.js
  frontend/src/Components/Common/Loader.js
  frontend/src/Components/Navbars/Navbar.js
  frontend/src/Router/PrivateRouter.js
  frontend/src/Styles/index.css
  frontend/src/Styles/loader.css
  frontend/src/index.js
Labels: client, enhancement

#60 Set Current User details globally
  backend/app/server/controllers/user.py
  backend/app/server/models/user.py
  backend/app/server/routes/user.py
  frontend/src/Components/UserFeed.js
  frontend/src/Context/AuthContext.js
  frontend/src/index.js
Labels: client, maintenance, server

#61 Notification Popups
  frontend/package.json
  frontend/src/App.js
  frontend/src/Components/Account/Login.js
  frontend/src/Components/Account/Register.js
Labels: client, enhancement

#62 Server (Python) and Client (JS) GH-Actions
  .github/workflows/linting.yml
  backend/requirements.txt
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Account/Register.js
Labels: client, enhancement, maintenance, server

#65 Route to get all posts
  backend/app/server/controllers/post.py
  backend/app/server/routes/post.py
Labels: enhancement, server

#69 Use NODE_ENV to deploy frontend
  frontend/package.json
  frontend/src/Components/Account/Login.js
  frontend/src/Components/Account/Register.js
  frontend/src/Context/AuthContext.js
  frontend/src/constants.js
Labels: client, enhancement, maintenance

#71 Flake8/ESLint Fixes
  backend/app/server/controllers/user.py
  backend/app/server/routes/user.py
  frontend/src/App.js
  frontend/src/Components/Account/Login.js
  frontend/src/Components/Account/Register.js
  frontend/src/Components/Navbars/Navbar.js
  frontend/src/Components/Utils/validations.js
  frontend/src/Context/AuthContext.js
  frontend/src/constants.js
Labels: client, maintenance, server

#73 Integration of Post with Comment component
  backend/app/server/controllers/comment.py
  backend/app/server/controllers/post.py
  backend/app/server/models/comment.py
  backend/app/server/models/post.py
  backend/app/server/routes/comment.py
  frontend/src/Components/Post/Comment.js
  frontend/src/Components/Post/CreateComment.js
  frontend/src/Components/Post/CreatePost.js
  frontend/src/Components/Post/Post.js
  frontend/src/Components/UserFeed.js
  frontend/src/Components/UserProfile.js
  frontend/src/Context/AuthContext.js
  frontend/src/constants.js
Labels: client, enhancement, server

#75 Default Avatar
  backend/.env.example
  backend/app/server/routes/user.py
Labels: enhancement, server

#76 Implement Like Logic in Frontend
  backend/app/server/controllers/like.py
  frontend/src/Components/Post/CreateComment.js
  frontend/src/Components/Post/Post.js
  frontend/src/constants.js
Labels: client, enhancement

#81 Singleton Config throughout the backend
  backend/app/server/config.py
  backend/app/server/controllers/auth.py
  backend/app/server/controllers/upload.py
  backend/app/server/database.py
  backend/app/server/routes/user.py
Labels: maintenance, server

#82 User profile component added
  frontend/src/Components/Common/Home.js
  frontend/src/Components/UserProfile.js
Labels: client, enhancement

#95 fix redirect issue with netlify
  frontend/public/_redirects
Labels: bug, client

#89 Verification of Posts (Server)
  backend/app/server/app.py
  backend/app/server/controllers/post.py
  backend/app/server/controllers/steganography/decode.py
  backend/app/server/controllers/steganography/encode.py
  backend/app/server/controllers/steganography/hash.py
  backend/app/server/controllers/steganography/transforms.py
  backend/app/server/controllers/upload.py
  backend/app/server/controllers/verify.py
  backend/app/server/models/post.py
  backend/app/server/routes/post.py
  backend/app/server/routes/verify.py
  backend/requirements.txt
Labels: enhancement, server

#99 Fix Likes Bug
  backend/app/server/controllers/like.py
  frontend/src/Components/Post/Post.js
Labels: bug, client

#101 Add Home Page
  frontend/src/Components/Account/Login.js
  frontend/src/Components/Account/Register.js
  frontend/src/Components/Common/Home.js
  frontend/src/Router/PublicRouter.js
Labels: client, enhancement

#104 Remove login route, update route to home on succesful registration
  frontend/src/Components/Account/Register.js
  frontend/src/Router/PublicRouter.js
Labels: client, maintenance

#79 Remove WebVitals, typo fixes
  README.md
  frontend/src/index.js
  frontend/src/reportWebVitals.js
Labels: documentation, enhancement

#106 Fix comments' alignment
  frontend/src/Components/Post/Comment.js
Labels: bug, client

#116 Fix bug in post ordering in Userfeed
  frontend/src/Components/UserFeed.js
Labels: bug, client

#120 Safer trigger for Greetings bot
  .github/workflows/greetings.yml
Labels: maintenance

#126 Drop dependency versions
  backend/requirements.txt
Labels: bug, maintenance, server

#123 Windows Fix - parse NODE_ENV
  frontend/package-lock.json
  frontend/package.json
Labels: bug, client

#118 PWA setup
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/src/Components/Account/Login.js
  frontend/src/index.js
  frontend/src/service-worker.js
  frontend/src/serviceWorkerRegistration.js
Labels: client, enhancement

#134 Linting via super-linter
  .github/linters/.flake8
  .github/workflows/linting.yml
  .github/workflows/lints.yml
  frontend/src/Components/Navbars/Navbar.js
  frontend/src/Components/UserFeed.js
  frontend/src/Components/UserProfile.js
  frontend/src/Context/AuthContext.js
Labels: bug, maintenance

#128 Default text for user profile
  frontend/src/Components/UserProfile.js
Labels: client, enhancement

#133 Changed website description
  frontend/public/index.html
Labels: client, documentation

#135 Update README with PWA details and screenshots
  README.md
Labels: documentation

#119 allow users to edit post
  backend/app/server/controllers/post.py
  backend/app/server/models/post.py
  backend/app/server/routes/post.py
  frontend/src/Components/Post/Post.js
  frontend/src/Styles/verification.css
  frontend/src/constants.js
Labels: client, enhancement

#136 Add report threshold
  backend/.env.example
  backend/app/server/config.py
  backend/app/server/controllers/post.py
Labels: enhancement, server

#124 Form values cleared after "Submit"
  frontend/src/Components/Account/Login.js
  frontend/src/Components/Account/Register.js
  frontend/src/Components/Navbars/Navbar.js
  frontend/src/Components/Post/CreatePost.js
Labels: client, enhancement

#132 Add CONTRIBUTING.md file
  CONTRIBUTING.md
  README.md
Labels: documentation

#144 Show Verification's User as a link
  frontend/src/Components/Post/Post.js
Labels: client, enhancement
